# Generated by Django 3.1.3 on 2023-12-05 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaDaVacinacao', models.TimeField()),
                ('dataDaVacinacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Aleitamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aleitamento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CrescimentoCrianca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idadeCrianca', models.CharField(max_length=20)),
                ('altura', models.FloatField()),
                ('peso', models.FloatField()),
                ('perimetro', models.FloatField()),
                ('imc', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDaCrianca', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14)),
                ('nomeDaMae', models.CharField(max_length=150)),
                ('cpfDaMae', models.CharField(max_length=14)),
                ('idadeCrianca', models.CharField(choices=[('primeira semana', 'primeira semana'), ('1 mês', '1 mês'), ('2 meses', '2 meses'), ('4 meses', '4 meses'), ('6 meses', '6 meses'), ('9 meses', '9 meses'), ('12 meses', '12 meses'), ('15 meses', '15 meses'), ('18 meses', '18 meses'), ('24 meses', '24 meses')], max_length=30)),
                ('maternidade', models.CharField(max_length=150)),
                ('tipoDoParto', models.CharField(max_length=150)),
                ('idadeGestacional', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('grauDeParentesco', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuidadosEspeciais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ferro', models.CharField(max_length=10)),
                ('micronutrientes', models.CharField(max_length=10)),
                ('vitaminaA', models.CharField(max_length=10)),
                ('odonto', models.CharField(max_length=10)),
                ('acidentesDomesticos', models.CharField(max_length=10)),
                ('negligencias', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CuidadosEspeciais2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_sono_24_horas', models.CharField(blank=True, max_length=255, null=True)),
                ('posicao_sono_berco', models.CharField(choices=[('NAO', 'NAO'), ('SIM', 'SIM')], default='NAO', max_length=50)),
                ('funcionamento_intestino_colicas', models.CharField(choices=[('PRESERVADO', 'PRESERVADO'), ('NAO_PRESERVADO', 'NAO PRESERVADO')], default='PRESERVADO', max_length=50)),
                ('higiene_cuidados_gerais', models.CharField(choices=[('PRESERVADO', 'PRESERVADO'), ('NAO_PRESERVADO', 'NAO PRESERVADO')], default='PRESERVADO', max_length=50)),
                ('sinais_violencias_negligencias', models.CharField(choices=[('PRESENTE', 'PRESENTE'), ('AUSENTE', 'AUSENTE')], default='AUSENTE', max_length=50)),
                ('acidentes_domiciliares', models.CharField(choices=[('NAO', 'NAO'), ('SIM', 'SIM')], default='NAO', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9)),
                ('numero', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=20)),
                ('complemento', models.CharField(max_length=100)),
                ('nomeUSF', models.CharField(default='USF', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExameOcular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('globo_ocular', models.CharField(choices=[('normal', 'Normal'), ('anormal', 'Anormal')], default='normal', max_length=10)),
                ('pupilas', models.CharField(choices=[('normal', 'Normal'), ('anormal', 'Anormal')], default='normal', max_length=10)),
                ('estrabismo', models.CharField(choices=[('nao', 'Não'), ('sim', 'Sim')], default='nao', max_length=5)),
                ('secrecao_ocular', models.CharField(choices=[('nao', 'Não'), ('sim', 'Sim')], default='nao', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='LeiteArtificial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parouAmamentar', models.CharField(max_length=10)),
                ('idadeParou', models.CharField(max_length=150)),
                ('alimentoCrianca', models.CharField(max_length=150)),
                ('porcoesFrutasDia', models.IntegerField()),
                ('alimentosIndustrializado', models.CharField(max_length=10)),
                ('qualAlimentoIndust', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeDoMedico', models.CharField(max_length=100)),
                ('Conselho', models.CharField(max_length=100)),
                ('Escilidade', models.CharField(max_length=100)),
                ('NumeroDeInscricao', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Telefone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='ProfissionalDeSaude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.CharField(max_length=150)),
                ('senha', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=11, unique=True)),
                ('tipoProfissional', models.CharField(max_length=150)),
                ('conselho', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SinaisAlerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diarreia', models.CharField(max_length=10)),
                ('vomitos', models.CharField(max_length=10)),
                ('dificuldadeRespirar', models.CharField(max_length=10)),
                ('febre', models.CharField(max_length=10)),
                ('hipotermia', models.CharField(max_length=10)),
                ('sibilancias', models.CharField(max_length=10)),
                ('convulcoes', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TriagemNeonatal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olhinho', models.CharField(choices=[('REALIZADO', 'REALIZADO'), ('NAOREALIZADO', 'NAOREALIZADO')], max_length=30)),
                ('data1', models.DateField()),
                ('olhodireito', models.CharField(choices=[('NORMAL', 'NORMAL'), ('ALTERADO', 'ALTERADO')], max_length=30)),
                ('olhoesquedo', models.CharField(choices=[('NORMAL', 'NORMAL'), ('ALTERADO', 'ALTERADO')], max_length=30)),
                ('obs1', models.CharField(max_length=150)),
                ('cardiopata', models.CharField(choices=[('REALIZADO', 'REALIZADO'), ('NAOREALIZADO', 'NAOREALIZADO')], max_length=30)),
                ('data2', models.DateField()),
                ('resultado', models.CharField(choices=[('NORMAL', 'NORMAL'), ('ALTERADO', 'ALTERADO')], max_length=30)),
                ('obs2', models.CharField(max_length=150)),
                ('auditiva', models.CharField(choices=[('REALIZADO', 'REALIZADO'), ('NAOREALIZADO', 'NAOREALIZADO')], max_length=30)),
                ('data3', models.DateField()),
                ('testes', models.CharField(choices=[('EMISSAO', 'EMISSAO'), ('POTENCIAL', 'POTENCIAL')], max_length=30)),
                ('ouvidodireito', models.CharField(choices=[('NORMAL', 'NORMAL'), ('ALTERADO', 'ALTERADO')], max_length=30)),
                ('ouvidoesquerdo', models.CharField(choices=[('NORMAL', 'NORMAL'), ('ALTERADO', 'ALTERADO')], max_length=30)),
                ('obs3', models.CharField(max_length=150)),
                ('pezinho', models.CharField(choices=[('REALIZADO', 'REALIZADO'), ('NAOREALIZADO', 'NAOREALIZADO')], max_length=30)),
                ('data4', models.DateField()),
                ('reteste', models.DateField()),
                ('pezinhoresultado1', models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO'), ('TALVEZ', 'TALVEZ')], max_length=30)),
                ('pezinhoresultado2', models.CharField(blank=True, choices=[('NORMAL', 'NORMAL'), ('ALTERADO', 'ALTERADO')], max_length=30, null=True)),
                ('orelhinharesultado', models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO'), ('TALVEZ', 'TALVEZ')], max_length=30)),
                ('orelhinharesultado2', models.CharField(blank=True, choices=[('NORMAL', 'NORMAL'), ('ALTERADO', 'ALTERADO')], max_length=30, null=True)),
                ('exameauditoresultado', models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO'), ('TALVEZ', 'TALVEZ')], max_length=30)),
                ('exameauditoresultado2', models.CharField(blank=True, choices=[('NORMAL', 'NORMAL'), ('ALTERADO', 'ALTERADO')], max_length=30, null=True)),
                ('olhinhoresultado', models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO'), ('TALVEZ', 'TALVEZ')], max_length=30)),
                ('olhinhoresultado2', models.CharField(blank=True, choices=[('NORMAL', 'NORMAL'), ('ALTERADO', 'ALTERADO')], max_length=30, null=True)),
                ('coracaozinhoresultado', models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO'), ('TALVEZ', 'TALVEZ')], max_length=30)),
                ('coracaozinhoresultado2', models.CharField(blank=True, choices=[('NORMAL', 'NORMAL'), ('ALTERADO', 'ALTERADO')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoVacina', models.CharField(max_length=150)),
                ('lote', models.CharField(max_length=150)),
                ('fabricante', models.CharField(max_length=150)),
                ('dataFabricacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeSaudeFamiliar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criadoEmDiaMesAno', models.DateField()),
                ('idCrianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.crianca')),
                ('idCuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.cuidador')),
                ('idEndereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.endereco')),
                ('idProfissionalDeSaude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.profissionaldesaude')),
            ],
        ),
        migrations.CreateModel(
            name='ProfissionalSaudeEUSF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criadoEmDiaMesAno', models.DateField()),
                ('idProfissionalDeSaude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.profissionaldesaude')),
                ('idUSF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.unidadesaudefamiliar')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoDeVacinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criadoEmDiaMesAno', models.DateField()),
                ('idAgendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.agendamento')),
                ('idVacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.vacina')),
            ],
        ),
        migrations.CreateModel(
            name='DesenvolvimentoInfantil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reflexo_moro', models.CharField(blank=True, choices=[('P', 'Presente'), ('A', 'Ausente'), ('NV', 'Não Verificado')], max_length=2)),
                ('reflexo_cocleo_palpebral', models.CharField(blank=True, choices=[('P', 'Presente'), ('A', 'Ausente'), ('NV', 'Não Verificado')], max_length=2)),
                ('reflexo_succao', models.CharField(blank=True, choices=[('P', 'Presente'), ('A', 'Ausente'), ('NV', 'Não Verificado')], max_length=2)),
                ('bracos_pernas_flexionados', models.CharField(blank=True, choices=[('P', 'Presente'), ('A', 'Ausente'), ('NV', 'Não Verificado')], max_length=2)),
                ('postura_cabeca_lateralizada', models.CharField(blank=True, choices=[('P', 'Presente'), ('A', 'Ausente'), ('NV', 'Não Verificado')], max_length=2)),
                ('observa_rosto', models.CharField(blank=True, choices=[('P', 'Presente'), ('A', 'Ausente'), ('NV', 'Não Verificado')], max_length=2)),
                ('reage_som', models.CharField(blank=True, choices=[('P', 'Presente'), ('A', 'Ausente'), ('NV', 'Não Verificado')], max_length=2)),
                ('eleva_cabeca', models.CharField(blank=True, choices=[('P', 'Presente'), ('A', 'Ausente'), ('NV', 'Não Verificado')], max_length=2)),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.crianca')),
            ],
        ),
        migrations.CreateModel(
            name='Desenvolvimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brincaEsconde', models.CharField(max_length=15)),
                ('objetosMao', models.CharField(max_length=15)),
                ('duplicaSilaba', models.CharField(max_length=15)),
                ('senta', models.CharField(max_length=15)),
                ('idCrescimentoCrianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.crescimentocrianca')),
            ],
        ),
        migrations.CreateModel(
            name='CuidadorCrianca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criadoEmDiaMesAno', models.DateField()),
                ('idCrianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.crianca')),
                ('idCuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.cuidador')),
            ],
        ),
        migrations.CreateModel(
            name='CriancaVacina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criadoEmDiaMesAno', models.DateField()),
                ('idCrianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.crianca')),
                ('idVacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.vacina')),
            ],
        ),
        migrations.AddField(
            model_name='crescimentocrianca',
            name='idCrianca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.crianca'),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDaConsulta', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('tempoConsulta', models.CharField(max_length=20)),
                ('idAgendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.agendamento')),
                ('idMedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.medico')),
                ('id_crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.crianca')),
            ],
        ),
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='agendado', max_length=10)),
                ('crianca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.crianca')),
                ('idAgendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.agendamento')),
                ('idVacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.vacina')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to='userapp.profissionaldesaude')),
            ],
        ),
    ]
